### ISSUE TITLE
להשלים דף בית לפי הפגמה

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#10]
- [ ] implement based on https://www.figma.com/file/u75Gztv7HQRo1Gka24cZZ7?node-id=367:15958&mode=design#498925831 - please keep the כניסת מנהל button somewhere
- [ ] תשאירו לי שם איפשהו כניסת מנהל
- [ ] יש TODO

**Comment by noam-honig** [comment]
@yblonder  please check

**Comment by yblonder** [comment]
Done
