### ISSUE TITLE
We should consider using the MUI standard for the buttons

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#15]
- instead of determining the color here, we should set the color scheme based on https://mui.com/material-ui/customization/color/, and then use the color variant such as success  etc... here: https://mui.com/material-ui/react-button/#color - what do you think?

- [ ] Use  Grid & Stack for Layout https://mui.com/material-ui/react-grid/

- [ ] Adjust font sizes based on guidance from figma creator: https://docs.google.com/presentation/d/1rC54inqQoNvhC4xwq9LID89wu3wHzoAv/edit?usp=sharing&ouid=110217017842037378670&rtpof=true&sd=true

Try to minimize customization on a component level - instead let's use Mul's stuff and let them take care of us

**Comment by Avnerussler** [comment]
@noam-honig I used it in theme.ts
<img width="395" alt="image" src="https://github.com/noam-honig/yedidia/assets/52633686/f8210a03-bda4-4505-8beb-344682bb850e">

**Comment by noam-honig** [comment]
I don't think that was the intention of Material Design.

I think we should have tagged these buttons as color="success" and have
Material design determine the color based on that.

And if we want the colors tweaked - we should weak the schema that we use

**Comment by noam-honig** [comment]
Also for font sizes and pretty much everything else - no?

**Comment by Avnerussler** [comment]
Yes-- בברכה,אבנר רוסלר | Avner Russlerנייד: 050-214-3427 Cellhttps://www.russler.coOn 17 Jul 2023, at 15:39, Noam Honig ***@***.***> wrote:﻿
Also for font sizes and pretty much everything else - no?

**Comment by noam-honig** [comment]
Yes

**Comment by Avnerussler** [comment]
@noam-honig I changed the mui theme configuration.. please take a look
