### ISSUE TITLE
Component dialog for messages

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#17]
- [ ] https://www.figma.com/file/u75Gztv7HQRo1Gka24cZZ7?node-id=293:28801&mode=design#499070076
- [ ] https://www.figma.com/file/u75Gztv7HQRo1Gka24cZZ7?node-id=1008:16394&mode=design#499070086

**Comment by Avnerussler** [comment]
@noam-honig How can I enforce a roll that you can’t send a poster without filling at last 2 fields?

**Comment by noam-honig** [comment]
An if statement here:
https://github.com/noam-honig/yedidia/blob/master/src/components/patientInfo.tsx#L61

**Comment by Avnerussler** [comment]
Yes I knew, but there is something built in inside remult?Right now we have an object of patient so I thought to check the values of the object.On 23 Jul 2023, at 21:35, Noam Honig ***@***.***> wrote:﻿
An if statement here:

https://github.com/noam-honig/yedidia/blob/master/src/components/patientInfo.tsx#L61



On Sun, Jul 23, 2023 at 9:16 PM Avner Russler ***@***.***>

wrote:

**Comment by noam-honig** [comment]
I wouldn't use remult for this - it should be an if statement and some semi
disabled rule

in general he wants that a button will appear disabled but will be
clickable, and when clicked, the user will see clear instructions.

Anyhow - do we have that dialog component|?

**Comment by Avnerussler** [comment]
No, I still need to style it On 23 Jul 2023, at 21:49, Avner Gmail ***@***.***> wrote:﻿Yes I knew, but there is something built in inside remult?Right now we have an object of patient so I thought to check the values of the object.On 23 Jul 2023, at 21:35, Noam Honig ***@***.***> wrote:﻿
An if statement here:

https://github.com/noam-honig/yedidia/blob/master/src/components/patientInfo.tsx#L61



On Sun, Jul 23, 2023 at 9:16 PM Avner Russler ***@***.***>

wrote:

**Comment by Avnerussler** [comment]
<img width="284" alt="image" src="https://github.com/noam-honig/yedidia/assets/52633686/54616044-f62b-41fe-9f50-68c5ce806720">

**I created the Dialog, I need the icons from the UI designer**

**Comment by noam-honig** [comment]
Can't you use the "copy as svg" from figma?

Also - the designer is also listening to issues, you can mention her (@) or
assign her

**Comment by Avnerussler** [comment]
No it’s not copied correctlyAlso the icons for the tiles doesn’t look very good, I played with the svg but still I don’t like itOn 24 Jul 2023, at 7:44, Noam Honig ***@***.***> wrote:﻿
Can't you use the "copy as svg" from figma?



Also - the designer is also listening to issues, you can mention her (@) or

assign her



On Mon, Jul 24, 2023 at 12:27 AM Avner Russler ***@***.***>

wrote:
