### ISSUE TITLE
מסך שנפתח כשמקבלים קישור מבת שירות

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#19]
- [ ] צריך כפתור יחסית גבוהה כדי שיהיה ברור לאן להכניס
- [ ] צריך טקסטים שמתאימים לזה.
- [ ]

**Comment by yblonder** [comment]
נראה לי מסך זהה לזה (שים לב להוספת כפתורי ליצירת פוסטר). 
כרגע אני מציע שכל מסכי הכניסה יהיו זהים 
![image](https://github.com/noam-honig/yedidia/assets/139717456/c38b9537-2fa0-468a-9e4b-d0ed0773f623)

**Comment by yblonder** [comment]
Done
