### ISSUE TITLE
התאמת טקסטים לבן משפחה של מטופל

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#20]
על כל שאלה כמה טקסטים:
- [ ] טקסט קצר שיופע במסך ריבועים
- [ ] טקסט שיופיע בפוסטר עצמו
- [ ] הסבר שיופיע כאשר מקלידים
- [ ] הסבר נוסף שיופיע כאשר מקלידים

- [ ] מצ"ב מצגת POWER POINT עם הטקסטים המעודכנים - יש להכיל אותם על הקוד 
https://docs.google.com/presentation/d/1CfC2_hSuC5qXzBJmK1uF7EArIUhNfWYU/edit?usp=sharing&ouid=110217017842037378670&rtpof=true&sd=true

**Comment by noam-honig** [comment]
@yblonder  בדודק

**Comment by yblonder** [comment]
- דף 2 במצגת (דף נחיתה) לא ברור לי איפה זה/איך מגיעים לזה.

**Comment by noam-honig** [comment]
@yblonder לחץ על יציאה ותראה אותו.

עוד דרך, במסך מחלקה, יש תפריט פתח קישור ליצירת טופס - שגם יראה לך דף כזה

**Comment by yblonder** [comment]
Done
