### ISSUE TITLE
הודעת SMS עבור תרחיש יצירה עצמית ושמירה למילוי עתידי

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#21]

**Comment by yblonder** [comment]
![image](https://github.com/noam-honig/yedidia/assets/139717456/093802b7-5a53-4364-a8f0-6c1a31bc2ceb)


שלום, 
אנחנו נציגים של המיזם ההתנדבותי 'נעים להכיר'. השירות שאנחנו מבצעים (חינם לגמרי) הוא הפקת פוסטרים אישיים של מאושפזים ומאושפזות ותלייתם ליד מיטות המטופלים. מטרת הפוסטר היא לעודד היכרות וקשר חם ואנושי יותר עם הצוות הרפואי.
אתם מוזמנים להעלות תמונות ותכנים נוספים לפוסטר של [שם המטופל/ת]. לפרטים נוספים ולהוספת התמונה לוחצים כאן > [לינק] 
תודה מראש על העזרה והרבה בריאות!

**Comment by noam-honig** [comment]
שוב - אני חושב שזה טקסט נורא ארוך להודעת SMS

**Comment by noam-honig** [comment]
@yblonder test

**Comment by yblonder** [comment]
הטקסט מופיע כולו כגוש אחד.  צריך לשבור אותו לפי התבנית הבאה:
שלום,
אנחנו נציגים של המיזם ההתנדבותי 'נעים להכיר'. 
השירות שאנחנו מבצעים (חינם לגמרי) הוא הפקת פוסטרים אישיים של מאושפזים ומאושפזות ותלייתם ליד מיטות המטופלים. 
מטרת הפוסטר היא לעודד היכרות וקשר חם ואנושי יותר עם הצוות הרפואי.
אתם מוזמנים להעלות תמונות ותכנים נוספים לפוסטר של [שם המטופל/ת]. 

לפרטים נוספים ולהוספת התמונה לוחצים כאן > [לינק]

תודה מראש על העזרה והרבה בריאות!
