### ISSUE TITLE
מסך מחלקה

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#23]
![image](https://github.com/noam-honig/yedidia/assets/16635859/cfefd779-62c8-45b4-ac5d-03c33b4a8b83)

- [x] תאריך יהיה תאריך יצירת הרשומה של מטופל
- [x] סטטוס, בשלב הראשון יציג V למי שיש לו ערך בשדה "תאריך אישור להדפסה" (שיעודכן כאשר לוחצים על הדפסה במסך ריבועים)
- [x] פעולות ברמת שורה
   - [ ] העבר לארכיון - יעדכן שדה ארכיון במטופל בTRUE (ולאחר רענון הוא יופיע בלשונית של ארכיון)
   - [x] ערוך פוסטר
   - [x] הצג פוסטר (יפתח את הPDF)
   - [x] שלח להדפסה (ישלח למייל הקבוע)
   - [x] שלח קישור להמשך מילוי יפתח את מסך "שליחת קישור להמשך מילוי" (ההסבר יופיע למטה במסמך זה)
- [x] כפתור הוספה:
   - [x] יפתח מסך להקלדת שם, וחדר
   - [x] יהיה כפתור "שליחת קישור להמשך מילוי" (ההסבר יופיע למטה במסמך זה)
   - [x] הכפתור אישור הרגיל יוביל לטופס למילוי
- [x] בתפריט העליון, 
   - [x] תהיה אפשרות להעתקת קישור למילוי עצמי עבור המחלקה, 
   - [ ] ואפשרות ליצירת QR למילוי עצמי עבור המחלקה
- [x] מסך "שליחת קישור להמשך מילוי" 
   - [x] יבקש מספר טלפון
   - [x] כפתור שליחה בSMS
   - [x] כפתור שליחה בווטסאפ
   - [x] אישור - סוגר את המסך ואת מסך ההוספה

**Comment by yblonder** [comment]
נראה לי מצויין. שליחת קישור לעריכה דרך ווטסאפ לא עובדת

**Comment by noam-honig** [comment]
@yblonder 
תוקן תבדוק בבקשה

**Comment by yblonder** [comment]
עובד
