### ISSUE TITLE
שיפורים במסך ריבועים

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#24]
- [x] כפתור הצג טופס, יפתח PDF בלשונית נפרדת - ויהיה פעיל בהתאם לחוקי הפעיל של המסך
- [x] כפתור סיום והדפסה, 
   - [x] יעדכן את שדה אישור הדפסה ויציג את מסך "הפוסטר נשלח בהצלחה" עם כפתור "הצג טופס" שיפתח PDF בלשונית נפרדת.
   - [x] וגם ישלח מייל למייל הקבוע על הטופס מצורף

![image](https://github.com/noam-honig/yedidia/assets/16635859/59ea7c51-29a3-4243-a330-0cade962e2d9)

**Comment by yblonder** [comment]
תוקן
