### ISSUE TITLE
להוריד את כפתור הביטול MODAL ולהפוך את אישור להמשך, כמו בפיגמה

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#25]
![image](https://github.com/noam-honig/yedidia/assets/16635859/d7460a98-297a-4d17-92b7-0194d7c6e5d9)

**Comment by noam-honig** [comment]
@yblonder please test

**Comment by yblonder** [comment]
הכפתורים עדיין מוסתרים. המחשבה היא שהם יופיעו מעל המקלדת הנפתחת כדוגמת זה: 
![image](https://github.com/noam-honig/yedidia/assets/139717456/4760a154-3b5b-4c28-b876-a44c51560597)


כרגע הם בצורה הזו: 
![image](https://github.com/noam-honig/yedidia/assets/139717456/06748f17-4811-4bbd-9cdb-02cc4dee4264)

**Comment by yblonder** [comment]
במידה ואין מקום - אפשר גם לעשות מצב בו חלק מהכפתור מופיע וחלק מוסתר (מצריך קצת גלילה) - זה ירמז למשתמשים שיש משהו נוסף המצריך גלילה. עדיפות להצגה מלאה של הכפתורים

**Comment by noam-honig** [comment]
זה קשור בכלל ל #37 

המיקוד של הISSUE הזה זה כפתור הביטול וההמשך - ממליץ שתאשר את זה @yblonder

**Comment by yblonder** [comment]
תוקן
