### ISSUE TITLE
תהליך חדש - קישור למילוי עצמי

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#26]
- [x] יהיה קישור נפרד לכל מחלקה, שמטופלים שנכנסים אליו יוכלו להקים לעצמם טופס - המחשבה היא שיהיה QR במחלקה, שפציינטים פשוט יוכלו לקרוא ולמלא את הטופס
- [x] יופיע המסך נעים להכיר הארוך
- [x] לחיצה על יצירת טופס מעבירה למסך בו מוזן:
   - [x] שם
   - [x] חדר
   - [x] טלפון לשליחת קישור להמשך מילוי
      - [x] לאפשר רק ספרות
      - [x] לעשות ולידציה שהטלפון תקין 
   - [x] ומשם ממשיך כרגיל
- [x] להוסיף אינדיקציה ברמת המטופל שהוא הגיע ממילוי עצמי
- [x] לאפשר משהו דומה בדף הבית - גם למטופלים ללא מחלקה, באופן שיאפשר להם למלא שאלון בלי תלות במחלקה - זה פשוט ישים מחלקה כללית שנגדיר עבור זה

**Comment by noam-honig** [comment]
@yblonder please test functionality

**Comment by yblonder** [comment]
נראה תקין
