### ISSUE TITLE
מספר חדר

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#28]
נראה שמספר חדר לא מופיע לצד השם (בסוגריים) וגם לא מופיע לאחר מכן בעריכה. 
![Screenshot_20230717_195732_Figma](https://github.com/noam-honig/yedidia/assets/139717456/7f983972-b5b6-4863-96aa-02c61ca613ce)

**Comment by noam-honig** [comment]
בדקתי עכשיו ואני לא רואה את זה - אולי זה כבר תוקן. תבדוק בבקשה:
@yblonder

**Comment by yblonder** [comment]
עובד יפה
