### ISSUE TITLE
מסך שיתוף בווטסאפ - טקסט

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#31]
ידידיה צריך לספק את הטקסט המתאים שם

**Comment by yblonder** [comment]
![image](https://github.com/noam-honig/yedidia/assets/139717456/b888d8e8-98f5-46ce-b3ed-b61d00b66c76)

**Comment by yblonder** [comment]
![image](https://github.com/noam-honig/yedidia/assets/139717456/c03aa94a-5c3c-44bb-baab-d70eedc5ea1a)

שלום, 
אנחנו נציגים של המיזם ההתנדבותי 'נעים להכיר'. השירות שאנחנו מבצעים (חינם לגמרי) הוא הפקת פוסטרים אישיים של מאושפזים ומאושפזות ותלייתם ליד מיטות המטופלים. מטרת הפוסטר היא לעודד היכרות וקשר חם ואנושי יותר עם הצוות הרפואי.
קיבלנו את המספר שלך מ[שם המזמין/ה] כדי להזמין אותך להעלות תמונות ותכנים נוספים לפוסטר של [שם המטופל/ת]. לפרטים נוספים ולהוספת התמונה לוחצים כאן > [לינק] 
תודה מראש על העזרה והרבה בריאות!

**Comment by noam-honig** [comment]
שווה לשקול שוב. האם זו ההודעה שנשלחת מהמטופל למישהו שיעזור לו או מהבת שרות.
לא חושב שהטקסט מתאים לשני המקרים

**Comment by noam-honig** [comment]
זה גם טקסט מאד מאד ארוך להודעת SMS

**Comment by yblonder** [comment]
ממליץ לשנות את הטקסט ל"קיבלנו את המספר שלך כדי להזמין אותך להעלות תמונות ותכנים נוספים לפוסטר של [שם המטופל/ת]."

**Comment by noam-honig** [comment]
צריך גם לכלול את הלינק בטקסט הזה.

אתה מוזמן לנסות לערוך ב:
https://github.com/noam-honig/yedidia/blob/7e926ad1552adcc7a6f08cf377883a57274362d0/src/model/patient.ts#L91
