### ISSUE TITLE
כפתורים מוסתרים ומצריכים גלילה 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#32]
![Screenshot_20230717_203636_Chrome](https://github.com/noam-honig/yedidia/assets/139717456/d0736019-c2c8-439f-a93f-2503ed9012f9)

יש צורך בגלילה בשביל לראות את הכפתורים כשמקלדת עולה. צריך להקטין את שדה הטקסט ואולי את הרווח בין הדברים לכפתורים (ראו פיגמה).

**Comment by yblonder** [comment]
הגבלת תווים צריכה להיות ל 300 תווים. ראו בפיגמה מה קורה כשעוברים את המכסה (לא ניתן להמשיך להקליד + יש חיווי)

**Comment by yblonder** [comment]
כפתור ביטול מיותר. כפתור אישור צריך.להיות המשך

**Comment by yblonder** [comment]
גודל הטקסטים נראה לי קטן מאד. האם אתם רוצים הגדרה ב pt או צורה אחרת מהגרפיקאית?

**Comment by noam-honig** [comment]
> הגבלת תווים צריכה להיות ל 300 תווים. ראו בפיגמה מה קורה כשעוברים את המכסה (לא ניתן להמשיך להקליד + יש חיווי)

פתחתי על זה ISSUE נפרד - #39

**Comment by noam-honig** [comment]
> כפתור ביטול מיותר. כפתור אישור צריך.להיות המשך
יש לזה כבר ISSUE #25

**Comment by noam-honig** [comment]
> גודל הטקסטים נראה לי קטן מאד. האם אתם רוצים הגדרה ב pt או צורה אחרת מהגרפיקאית?
יש ISSUE של סידור הפונטים כחלק מ #15

**Comment by noam-honig** [comment]
אקיצר כל מה שכתוב פה מכוסה בISSUES אחרים :) - סוגר את זה

**Comment by noam-honig** [comment]
> ![Screenshot_20230717_203636_Chrome](https://user-images.githubusercontent.com/139717456/254023152-d0736019-c2c8-439f-a93f-2503ed9012f9.jpg)
> 
> יש צורך בגלילה בשביל לראות את הכפתורים כשמקלדת עולה. צריך להקטין את שדה הטקסט ואולי את הרווח בין הדברים לכפתורים (ראו פיגמה).

אה כן - זה בא לידי ביטוי ב #37
