### ISSUE TITLE
הצג פוסטר 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#33]
לאחר עריכה, יש להיכנס שוב לשדה העריכה ולאשרו בשביל לראות את זה בפוסטר

**Comment by noam-honig** [comment]
לדעתי זה היה בגלל זה שהשמירה עוד לא הסתיימה והיתה איטית - שיפרתי שם. תבדוק שוב? @yblonder

**Comment by yblonder** [comment]
הסתדר
