### ISSUE TITLE
טקסט שונה עבור מקרה של טופס שלא שייך למחלקה

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#36]
במקרה שבו אדם מהציבור הגיע לאתר ויצר לעצמו טופס - הרי אין לנו איך להדפיס ולשלוח אליו - צריך אולי טקסט אחר
![image](https://github.com/noam-honig/yedidia/assets/16635859/f42f7c7c-4cc1-44ae-80ea-1252c50254db)

**Comment by yblonder** [comment]
הפוסטר נוצר בהצלחה

בחרתם לא לשייך את הפוסטר לאחד המוסדות שאנחנו עובדים איתם. 
נשמח שתציעו למוסד בו יקירכם מאושפז להצטרף אלינו (השירות ללא עלות, גם עבורם). 
בינתיים אתם מוזמנים להוריד את הפוסטר על ידי לחיצה על "הצג פוסטר", להדפיסו באופן עצמאי ולתלות אותו לצד יקירכם. 
רפואה שלמה! 

צוות נעים להכיר

**Comment by yblonder** [comment]
כרגע אין דרך להגיע למצב כזה היות ויש צורך בתפריט drop down של כלל המוסדות ולבחור שם "אחר"

**Comment by noam-honig** [comment]
אני חושב שאתה טועה - כרגע אין DROP DOWN של מחלקות - וגם לא חושב שצריך שיהיה.

לכל מחלקה יש קישור שלה - שאז המטופלים נרשמים אליה

ויש גם את דף הבית - שבו אדם נרשם ושם אתה לא יודע איך ולמי להדפיס - ולכן הוא צריך להדפיס לבד

@yblonder

**Comment by yblonder** [comment]
מסכים. במקרה כזה אני מציע שהטקסט על הכפתור יהיה "הורד פוסטר" - מה דעתך?

**Comment by noam-honig** [comment]
@yblonder please test

**Comment by yblonder** [comment]
תוקן
