### ISSUE TITLE
להתאים את המערכת מבחינת גדלים וSCROLL כך שאפשר יהיה למלא בכל מצב

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#37]
כרגע כאשר הופכים את הטלפון לאופקי, וכו... יש מלא מקומות שאי אפשר להשתמש במערכת והכפתורים לא נמצאים במקום הנכון. צריך לטפל בזה גם בטופס וגם בCUSTOM DIALOG

![image](https://github.com/noam-honig/yedidia/assets/16635859/0f91f099-f1af-44f6-a821-3effd0d178ef)
וכשעושים SCROLL:
![image](https://github.com/noam-honig/yedidia/assets/16635859/8fb5d6fb-22d3-4581-9a3f-f648e5540c5e)

במסך הבא אי אפשר בכלל ללחוץ אישור:
![image](https://github.com/noam-honig/yedidia/assets/16635859/fd034e39-0d28-4299-b02a-accf22d9df6e)

וזה עם מקלדת:
![image](https://github.com/noam-honig/yedidia/assets/16635859/273ee8d1-be88-4cab-a395-96b9349c27ab)

אפשר לסמלץ את זה בCHROME על ידי הוספת אמולציה לטלפון nexus 5 ואז בלחיצה על הICON אפשר לבחור את המצבים השונים
![image](https://github.com/noam-honig/yedidia/assets/16635859/bd606efc-2ff6-45a6-a2c8-e061dedf1d62)

**Comment by noam-honig** [comment]
@yblonder please check

**Comment by yblonder** [comment]
תוקן. גם העבודה האופקית עובדת יחסית בסדר ולדעתי אין צורך בשיפור של זה כרגע
