### ISSUE TITLE
הגבלת תווים צריכה להיות ל 300 תווים. ראו בפיגמה מה קורה כשעוברים את המכסה (לא ניתן להמשיך להקליד + יש חיווי)

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#39]
הגבלת תווים צריכה להיות ל 300 תווים. ראו בפיגמה מה קורה כשעוברים את המכסה (לא ניתן להמשיך להקליד + יש חיווי)

_Originally posted by @yblonder in https://github.com/noam-honig/yedidia/issues/32#issuecomment-1638589008_

**Comment by Avnerussler** [comment]
Duplicht
