### ISSUE TITLE
סיום והדפסה

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#40]
בלחיצה על סיום והדפסה לוקח הרבה זמן עד למעבר למסך הבא. אם יש צורך בזמן עבור יצירת הפוסטר אני מציע לעבור למסך הבא מהר וברקע לייצר אותו.  אם נצטרך זמן נוסף לפני הצג, נשים שם חיווי של טעינה animated gif

**Comment by noam-honig** [comment]
@yblonder  תוקן - תבדוק בבקשה

**Comment by yblonder** [comment]
עובד יפה
