### ISSUE TITLE
אייקונים למסך מחלקה

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#41]
הי הילית, חסר לי ICONS למסך מחלקה - לתפריט ברמת השורה:
![image](https://github.com/noam-honig/yedidia/assets/16635859/3b719471-774c-4257-b321-85cf78c51195)

וגם לתפריט השמאלי:
![image](https://github.com/noam-honig/yedidia/assets/16635859/281c6441-481e-41ec-aff5-7a305a419469)

**Comment by ililh** [comment]
uploaded
![image](https://github.com/noam-honig/yedidia/assets/140059973/4be764e3-fe5b-4ee8-9699-5e9aac09d7c1)
