### ISSUE TITLE
fix style for sending link to continue filling

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#42]
המסך הבא מופיע לנציג מחלקה כאשר הוא רוצה להעביר קישור למשפחה / מטופל / מישה אחר שימלא את הטופס.

![image](https://github.com/noam-honig/yedidia/assets/16635859/ec7d0c5b-6ea9-465c-8eae-3c454fe42313)

יש שתי שיטות שליחה - זה נראה בסדר, או שהיית רוצה אחרת?

**Comment by ililh** [comment]
ריווח בין הכפתורים וגם להוסיף את האיקונים של הוואטסאפ והסמס
הירוק של הכפתורים בהיר מדי, צריך לתקן לפי הצבע הירוק העכשווי #007B1B
![image](https://github.com/noam-honig/yedidia/assets/140059973/ee0801e7-6148-4312-bda8-32935b924f96)
