### ISSUE TITLE
  שיתוף בווטסאפ להעלאת תמונה 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#44]
![Screenshot_20230720_211139_Chrome](https://github.com/noam-honig/yedidia/assets/139717456/8394ec40-dd0f-47f0-b886-77f918af2dcf)

כדאי להוסיף כאן כפתור "המשך עריכה" שיחזיר למסך הראשי של הריבועים.

**Comment by noam-honig** [comment]
לא חושב. בדיק כמו שהורדנו את הביטול. החץ למעלה מחזיר להמשך עריכה

**Comment by yblonder** [comment]
זה נראה לי מצב שונה. במקרה הזה המשתמש יצא מהאפליקציה למסך אחר (ווטסאפ) ואז חוזר. זה מייצר מעין ניתוק שכדאי לעזור בו בהוראה מכוונת שמשמעותה שהוא וכדאי שבינתיים ימשיך לערוך ולהוסיף.

**Comment by noam-honig** [comment]
@yblonder הוספתי כפתור המשך כמו במסכים האחרים

**Comment by yblonder** [comment]
לדעתי כפתור ההמשך צריך להופיע רק לאחר לחיצה על שתף בווטסאפ (כלומר להיות שם אחרי שהוא שיתף). בנוסף זה צריך להוביל חזרה למסך הראשי ולא אחורה למסך העלאת תמונה (המשתמש בשיתוף בעצם "הכריז" שאין לו תמונה להעלות)

**Comment by noam-honig** [comment]
@yblonder Please test

**Comment by yblonder** [comment]
done
