### ISSUE TITLE
character limit

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#45]
צריך להגביל ל 300 תווים ואז להציג הודעה - ראו בפיגמה  
![Screenshot_20230720_211516_Chrome](https://github.com/noam-honig/yedidia/assets/139717456/6621ee07-7195-463f-8cad-ed4090f24956)

**Comment by Avnerussler** [comment]
הכוונה להגביל ל500 תווים? לפי הפיגמה אין הגבלה, פשוט אחרי 500 תווים תופיע שגיאה
השאלה האם להגביל ממש או לא להגביל ורק להוסיף הודעת שגיאה
@yblonder

**Comment by yblonder** [comment]
הכוונה היא להגביל ממש ולהציג את ההודעה כשמגיעים לקצה. בנוסף הכמות צריכה
להיות 300 ולא 500.

**Comment by yblonder** [comment]
נראה שזה עדיין לא עובד 
![Uploading Screenshot_20230723_000312_Chrome.jpg…]()

**Comment by Avnerussler** [comment]
זה עדיין לא מורג׳ג׳אתה בודק את הקוד של הבראנץ הזה?--On 23 Jul 2023, at 0:04, yblonder ***@***.***> wrote:﻿
נראה שזה עדיין לא עובד
