### ISSUE TITLE
שליחת קישור מתוך מנהל 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#46]
נראה ששליחת קישור ווטסאפ לא עובדת 
![Screenshot_20230720_212435_Chrome](https://github.com/noam-honig/yedidia/assets/139717456/df2c8829-820f-41ac-bde9-c6169e3cb098)

**Comment by noam-honig** [comment]
@yblonder תוקן - תבדוק בבקשה

**Comment by yblonder** [comment]
עובד
