### ISSUE TITLE
מיילים עלתפוסטרים שנשלחו להדפסה 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#47]
אני לא רואה אותם ב posternaim@gmail.com 
האם יש מקום שאני אמור להגדיר את זה למחלקה?

**Comment by noam-honig** [comment]
@yblonder 
עשיתי כמה בדיקות הבוקר, ונראה שזה נשלח בהצלחה. 

הוספתי גם אותי בCC והמיילים הגיעו.

1. תבדוק בבקשה בSPAM.
2. אם טופס ספציפי לא נשלח, תגיד אני אבדוק.

**Comment by yblonder** [comment]
עובד, מגיע לספאם.
