### ISSUE TITLE
העלאת תמונה - מעבר למסך ראשי

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#48]
לאחר לחיצה על המשך במסך זה , לוקח הרבה זמן עד שעוברים למסך הבא (כ 5 שניות). אם אי אפשר לקצר זאת משמעותית (בערך ל1.5 שניות או פחות) צריך שנוסיף חיווי לטעינה. 
![Screenshot_20230720_230019_Chrome](https://github.com/noam-honig/yedidia/assets/139717456/77bd29ce-f6a0-46a7-9fe1-4af0efba8a2a)

**Comment by noam-honig** [comment]
@yblonder שופר

גם זה סוגר עכשיו את המסך ומאפשר להמשיך לעבוד - וגם הוספתי אינדיקציה לטעינה, בקוביה של התמונה

תבדוק

**Comment by yblonder** [comment]
עובד
