### ISSUE TITLE
Improve width for desktop

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#5]
אנחנו צריכים לגרום לזה להראות בדקטופ כמו בנייד - כלומר כמו שהגבלנו את הרוחב של הפוסטר - אני רוצה את הכל, גם התפריט למעלה וגם האזור של כפתורי השמירה וביטול ואישור וכו... שיראה כאילו אנחנו בVM של נייד :)
![image](https://github.com/noam-honig/yedidia/assets/16635859/63f7ade6-66e1-45d1-925f-b29c37a9f854)

**Comment by noam-honig** [comment]
Done

**Comment by yblonder** [comment]
Done
