### ISSUE TITLE
כפתור המשך - מסך.תנאים 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#50]
הכפתור צריך להיות disabled כשלא מסומן הצ'ק בוקס. לחיצה עליו המצב לא מסומן תציג את ההודעה הקיימת כרגע.

**Comment by noam-honig** [comment]
שאלת ux. לפעמים אני רואה כפתור דיסאבלד ולא מבין למה. לא עדיף לחיות עליו ושיסביר לי למה?

**Comment by yblonder** [comment]
נראה לי שההצעה שלי נותנת מענה יחסית טוב. מי שמכיר את זה המצב יבין שמשהו חסר
ויסמן וגם יבין שזה תנאי.  מי שלא, יקבל את ההודעה.
לקבל את ההודעה זה אופציה ב', יש בה משהו חריף יותר ועדיף שהמשתמש יעלה על זה
לבד.

**Comment by noam-honig** [comment]
אני לא משוכנע שכאשר הכפתור הוא DISABLED אפשר בכלל ללחוץ עליו - אולי צריך
לעשות לו איזה שהיא נוסחת צבע

**Comment by yblonder** [comment]
נשמע לי שנוסחת צבע מתאימה במידה וזה לא לחיץ. נראה לי שהכחול הנוכחי מתאים למצב הדיסאבלד.

**Comment by noam-honig** [comment]
@yblonder  please test

**Comment by yblonder** [comment]
הכפתור צריך להיות בצבע הdisabled בכל מצב שהצ'ק בוקס לא מסומן. כרגע הוא הופך לצבע הזה רק כשלוחצים עליו. 
@ililh  תוכלי לתת בבקשה הגדרת עיצוב לכפתור במצב הזה?

**Comment by noam-honig** [comment]
אני על זה. כמו במסך הרגיל

**Comment by noam-honig** [comment]
@ililh already have an indication on how disabled should look A.4 opacity I think. I’ll look at the code

**Comment by yblonder** [comment]
תוקן
