### ISSUE TITLE
העלאת תמונה

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#51]
במעבר למסך הראשי לא מוצגת אנימציה טעינה

**Comment by noam-honig** [comment]
![image](https://github.com/noam-honig/yedidia/assets/16635859/8e56e4d4-2943-4dab-9567-cacb7838a36e)
זו האינדיקציה שעשיתי כל עוד התמונה עולה 

לזה התכוונת?
@yblonder

**Comment by yblonder** [comment]
כן

**Comment by noam-honig** [comment]
זה לא מוצג כי זה רץ מהר. כנראה את. ליד אינטרנט טוב :)

**Comment by noam-honig** [comment]
הבעיה בהעלאת תמונה כאשר לא היתה תמונה קודם

**Comment by noam-honig** [comment]
@yblonder fixed - please check

**Comment by yblonder** [comment]
done
