### ISSUE TITLE
הוסף קטע אודות ב-readme 

### ISSUE THREAD

**Issue by Yedidyar** [noam-honig/yedidia#55]
היי ניסיתי להבין על מה הפרויקט ולא כל כך הבנתי. 
אשמח שתוסיפו אם אפשר

תודה

**Comment by yblonder** [comment]
@noam-honig איפה הטקסט הזה אמור להופיע. מי רואה את זה ? באיזו שפה . תוכל להראות לי דוגמא - למשל של אפליקציית חגי?

**Comment by noam-honig** [comment]
תסתכל כאן בפרוייקט הזה בגיטהאב

**Comment by yblonder** [comment]
הקישור לא פתוח לי לתצוגה. אנא שלח לי דוגמא של טקסט כזה ואנסח משהו קצר לפרויקט שלנו.

**Comment by yblonder** [comment]
אני מציע את הטקסט הבא: מיזם ההתנדבותי 'נעים להכיר'. השירות שאנחנו מבצעים (חינם לגמרי) הוא הפקת פוסטרים אישיים של מאושפזים ומאושפזות ותלייתם ליד מיטות המטופלים. מטרת הפוסטר היא לעודד היכרות וקשר חם ואנושי יותר עם הצוות הרפואי.

**Comment by noam-honig** [comment]
מציע לנסח מחדש. ״השירות זאנחנו מבצעים״ זו סתם תשובה לשאלה שלא נשאלה.

יותר משהו כמו אנחנו מפיקים פוסטרים אישיים…..

**Comment by yblonder** [comment]
מסכים.  

'נעים להכיר' הינו מיזם התנדבותי שמטרתו יצירת קשר חם ואנושי יותר בין מאושפזים ומאושפזות לצוות הרפואי. המיזם מפיק, בעזרת המערכת, פוסטרים אישיים של המטופלים שמציגים אותם כאדם (ולא רק כמטופל) ודואג לתלייה שלהם לצד מיטת האשפוז ובכך מעודד יצירת קשר כזה.

**Comment by yblonder** [comment]
@noam-honig האם הכנסת את הטקסט הזה? אם כן אפשר לסגור. (אני לא יודע איפה אמורים להכניס)

**Comment by noam-honig** [comment]
מדובר על הקובץ הסבר לפרוייקט הקוד פתוח - לא בטוח שמעניין אותך, אבל אם כן הקישור לעריכה נמצא כאן:
https://github.com/noam-honig/yedidia/edit/master/README.md

והטקסט זה הטקסט שמופיע באתר של הקוד:
https://github.com/noam-honig/yedidia/
