### ISSUE TITLE
הגבלת תווים

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#61]
1. בבקשה לצמצם את הגבלת התווים ל 250 (במקום 300). 
2. ספירת התווים צריכה לכלול רווחים / שבירת שורה כאילו זה תו (אחרת זה יצא מהאזור הרלוונטי בפוסטר). כלומר כך שורה שהמשתמש יורד נספרת כשורת תווים מלאה.

**Comment by noam-honig** [comment]
2 זה לא משהו שאנחנו יכולים לעשות.
אפשר להגביל את מספר השורות ולנסות להעריך את האורך אבל זה לא יהיה מושלם

**Comment by noam-honig** [comment]
עשיתי את התוים - בוא נתחיל ככה, אם נראה שזה לא מספיק טוב נחשוב על משהו אחר

**Comment by yblonder** [comment]
בסדר גמור. 
המצב כרגע הוא שההודעה מוצגת רק בתו מספר 251 ולאחר מכן אין הצגה שלה. האם אפשר להשאיר את ההודעה כל זמן שעברנו את מכסת ה 250 תווים?

**Comment by noam-honig** [comment]
תוקן עכשיו

**Comment by yblonder** [comment]
Done
