### ISSUE TITLE
כפתור יציאה מתוך מסך מחלקה 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#62]
הכפתור יציאה בתוך תפריט ההמבורגר במסך מחלקה לא עובד 
בתוך רשימת המחלקות הכפתור עובד

**Comment by noam-honig** [comment]
Fixed. Waiting for deploy

**Comment by noam-honig** [comment]
@yblonder תוקן

**Comment by yblonder** [comment]
תוקן
