### ISSUE TITLE
כפתורים במסך הבית מצריכים גלילה

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#63]
הכפתורים בתחתית מסך הבית מצריכים גלילה גם בסלולר בעל מסך גדול. הם אמורים להיכנס 

![image](https://github.com/noam-honig/yedidia/assets/139717456/bedd92a4-2d9a-4785-90dc-78c6dc84c631)

**Comment by noam-honig** [comment]
@yblonder fixed

**Comment by yblonder** [comment]
תוקן
