### ISSUE TITLE
טקסטים מסך ראשי

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#66]
![image](https://github.com/noam-honig/yedidia/assets/139717456/8dbf9ef8-9ea8-4d25-ba6f-8a76f29ab74a)

- טקסטים מתחת לריבועי תמונה חסרים 
- - טקסט רקע ותחומי עניין חתוך (להקטין גודל של כולם כך שייכנס)

**Comment by noam-honig** [comment]
@yblonder בעיצוב לא היה טקסטים מתחת לתמונה

<img width="249" alt="image" src="https://github.com/noam-honig/yedidia/assets/16635859/f9ef2dc5-b025-44dc-97a3-8c50ab0bd0b9">

**Comment by noam-honig** [comment]
תיקנתי את הטקסט, והתאמתי את זה שזה יגדל יפה במסך רגיל

**Comment by yblonder** [comment]
Done
