### ISSUE TITLE
Fonts question

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#69]
Hi @ililh , @yblonder 

The figma uses a hebrew version that is not available on the web.
We agreed to use rubik instead:
https://fonts.google.com/specimen/Rubik

I just looked into my older pdf code, and it uses a font called NotoSansHebrew
https://fonts.google.com/noto/specimen/Noto+Sans+Hebrew

Is it important to have consistency between the two? of so, which do you prefer?

**Comment by ililh** [comment]
Rubik is good

**Comment by noam-honig** [comment]
Already done
