### ISSUE TITLE
חזרה מפוסטר לדוגמא 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#70]
במסך פוסטר לדוגמא (שנפתח מהמסך הראשי) צריך כפתור "חזרה"

**Comment by noam-honig** [comment]
הוא נפתח בלשונית אחרת - זה די נהוג

**Comment by noam-honig** [comment]
סודר - יש כפתור חזור
@yblonder

**Comment by yblonder** [comment]
תוקן
