### ISSUE TITLE
להשלים את מסך אודות בהתאם לפיגמה

### ISSUE THREAD

**Issue by noam-honig** [noam-honig/yedidia#8]
About.tsx

**Comment by noam-honig** [comment]
@yblonder  please test

**Comment by yblonder** [comment]
הטקסט צריך להיות זה: 

'נעים להכיר' הוא מיזם התנדבותי וחינמי המעודד היכרות טובה יותר בין מאושפזים לצוותים רפואיים, באמצעות פוסטר המציג את המאושפזים בדרך שנעימה להם.
הפוסטר מהדק את הקשר עם המטפלים נותן תקווה לשיקום ואפילו משפר את הטיפול.
אנחנו מקווים שהפוסטר יעשה לכם טוב, יעורר תקווה ויקל על כולכם ולו במעט.

רוצים לצרף את 'נעים להכיר' לארגון שלכם או להצטרף לצוות המתנדבים שלנו – כתבו לנו ל [posternaim@gmail.com](mailto:posternaim@gmail.com)

ואז החלק שיש עכשיו על חגי.

**Comment by noam-honig** [comment]
תוקן

**Comment by yblonder** [comment]
Done
