### ISSUE TITLE
תנאי שימוש ומדיניות הפרטיות 

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#84]
זה הטקסט שצריך להופיע בקישור: 

הנני נותן/נותנת בזאת הסכמתי להשתמש בפרטים האישיים והתמונות שאני מעלה למערכת "נעים מאד" עבור יצירת פוסטר. 

אני מסכים/מסכימה שהפוסטר ייתלה ליד מיטתי באופן שהצוות הטיפולי הניגש למיטתי יוכל לקרוא את הפרטים הרלוונטיים עלי ויכיר אותי טוב יותר. 

במידה ואבקש, הפרטים האישיים יימחקו מהמערכת והפוסטר יוסר. 

במתן הסכמתי זאת אני משחרר את "נעים מאד", המרכז הרפואי ו/או עובדיה ו/או כל מי שפועל מטעמה ו/או בשליחותה מכל טענה ו/או תביעה בקשר לחובת סודיות ו/או פגיעה בפרטיות ו/או כל הקשור ו/או הנובע מכך.

**Comment by yblonder** [comment]
יש צורך להחליף כאן את "נעים מאד" ל"נעים להכיר" ב 2 מקומות בטקסט (טעות שלי...). 
במסך "תרגומים" ערכתי את הטקסט אך כפתור "שמור" לא עובד

**Comment by noam-honig** [comment]
סידרתי שאפשר יהיה לעדכן - תנסה עכשיו ותבדוק @yblonder

**Comment by yblonder** [comment]
תוקן
