### ISSUE TITLE
קבלת אימייל בעת הדפסת פוסטר

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#85]
נראה שכרגע המערכת לא שולחת מיילים

**Comment by yblonder** [comment]
תוקן

**Comment by yblonder** [comment]
המערכת שולחת מיילים. הקובץ המצורף מופיע כ "טוען" ללא תוכן 
![image](https://github.com/noam-honig/yedidia/assets/139717456/957bfd3a-d877-4d3c-8368-3ded0ab67fdf)

**Comment by noam-honig** [comment]
Fixed

**Comment by yblonder** [comment]
fixed
