### ISSUE TITLE
צור PDF

### ISSUE THREAD

**Issue by yblonder** [noam-honig/yedidia#86]
לא ברור לי משמעות הכפתור הזה לאחר הצג PDF.

**Comment by noam-honig** [comment]
הכפתור הראשון הוא הצג פוסטר, הוא מראה אותו אבל לא בצורת pdf. הצור pdf -
יוצר אותו

**Comment by yblonder** [comment]
מבחינת המשתמש מה המשמעות של זה? זה שזה לא ירד אליו? אולי זה צריך להיות "הורד פוסטר" או "שמור פוסטר". מה דעתך?

**Comment by yblonder** [comment]
שיניתי ל"הורד פוסטר"
